# Generated by Django 5.2.10 on 2026-02-04 06:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('address', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='CartridgeModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=80)),
                ('code', models.CharField(max_length=120)),
                ('title', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('cartridge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='global_stock', to='inventory.cartridgemodel')),
            ],
        ),
        migrations.CreateModel(
            name='PrinterModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=80)),
                ('model', models.CharField(max_length=120)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('vendor', 'model'), name='uniq_printer_model')],
            },
        ),
        migrations.AddField(
            model_name='cartridgemodel',
            name='compatible_printers',
            field=models.ManyToManyField(blank=True, related_name='compatible_cartridges', to='inventory.printermodel'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=30)),
                ('owner_name', models.CharField(blank=True, max_length=255)),
                ('owner_email', models.EmailField(blank=True, max_length=254)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='inventory.building')),
            ],
        ),
        migrations.CreateModel(
            name='Printer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inventory_tag', models.CharField(blank=True, max_length=80)),
                ('note', models.TextField(blank=True)),
                ('printer_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printers', to='inventory.printermodel')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='printers', to='inventory.room')),
            ],
        ),
        migrations.CreateModel(
            name='StockTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tx_type', models.CharField(choices=[('IN', 'Приход'), ('OUT', 'Выдача')], max_length=3)),
                ('qty', models.PositiveIntegerField()),
                ('issued_to', models.CharField(blank=True, max_length=255)),
                ('comment', models.TextField(blank=True)),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.building')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transactions', to='inventory.cartridgemodel')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_transactions', to=settings.AUTH_USER_MODEL)),
                ('printer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='inventory.printer')),
            ],
        ),
        migrations.CreateModel(
            name='BuildingStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qty', models.PositiveIntegerField(default=0)),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='inventory.building')),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='building_stocks', to='inventory.cartridgemodel')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('building', 'cartridge'), name='uniq_building_stock')],
            },
        ),
        migrations.AddConstraint(
            model_name='cartridgemodel',
            constraint=models.UniqueConstraint(fields=('vendor', 'code'), name='uniq_cartridge_model'),
        ),
        migrations.AddConstraint(
            model_name='room',
            constraint=models.UniqueConstraint(fields=('building', 'number'), name='uniq_room_in_building'),
        ),
    ]
