# Generated by Django 5.2.11 on 2026-02-18 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='on_balance',
            field=models.BooleanField(default=False, help_text='Отметьте, если эти картриджи поступают на баланс школы', verbose_name='Постановка на баланс'),
        ),
    ]
