# Generated by Django 5.2.11 on 2026-02-18 08:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_stocktransaction_on_balance'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='buildingstock',
            name='uniq_building_stock',
        ),
        migrations.AddField(
            model_name='buildingstock',
            name='on_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='globalstock',
            name='on_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='globalstock',
            name='cartridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='global_stocks', to='inventory.cartridgemodel'),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='on_balance',
            field=models.BooleanField(default=False),
        ),
        migrations.AddConstraint(
            model_name='buildingstock',
            constraint=models.UniqueConstraint(fields=('building', 'cartridge', 'on_balance'), name='uniq_building_stock_balance'),
        ),
        migrations.AddConstraint(
            model_name='globalstock',
            constraint=models.UniqueConstraint(fields=('cartridge', 'on_balance'), name='uniq_global_stock_cartridge_balance'),
        ),
    ]
