# Generated by Django 5.2.11 on 2026-02-27 09:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_remove_buildingstock_uniq_building_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocktransaction',
            name='building_snapshot',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='issued_to_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='printer_inventory_tag_snapshot',
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='printer_model_snapshot',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stocktransaction',
            name='room_snapshot',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='cartridge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='inventory.cartridgemodel'),
        ),
    ]
